main/urls.py
from django.conf.urls import url
from django.urls import path

from django.contrib.auth.decorators import login_required

from main import views as m_views

urlpatterns = [
    path('', login_required(m_views.TodoListView.as_view()), name="home"),
    path('completed_todos', m_views.CompletedTodoListView.as_view(), name="completed_todos"),
    path('category/<int:category_id>', m_views.category_template, name="category_template"),

    path('ajax/add_new', m_views.add_new_ajax, name="add_new_ajax"),
    path('ajax/delete_todo/<int:todo_id>/', m_views.delete_todo_ajax, name="delete_todo_ajax"),
    path('ajax/complete_todo/<int:todo_id>/', m_views.complete_todo_ajax, name="complete_todo_ajax"),
]

todolist/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users.views import RegisterView, ProfileView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('profile/', ProfileView.as_view(), name="profile"),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),

    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/templates/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")    

    def __str__(self):
        return self.title


class Todo(models.Model):
    added_date = models.DateTimeField(blank=True, null=True)
    text = models.CharField(max_length=256)
    status = models.BooleanField(default=False)
    user_id = models.IntegerField(default=0)
    deadline = models.DateTimeField(blank=True, null=True, default=timezone.now().strftime("%Y-%m-%d"))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

main/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta():
        model = Todo
        fields = ('text', 'category', 'deadline')

main/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import ListView, CreateView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.models import User

from .models import Todo, Category
from .forms import TodoForm
from users.models import Profile


class TodoListView(ListView):
    model = Todo
    template_name = 'main/todo_list.html'
    context_object_name = 'todo_items'
    form = TodoForm

    def get_context_data(self, **kwargs):
        todo_items = Todo.objects.filter(
            status=False,
            user_id=self.request.user.id
        ).order_by("deadline")[:5]

        completed_items = Todo.objects.filter(
            status=True,
            user_id=self.request.user.id
        ).order_by("-added_date")[:5]

        category_list = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['todo_items'] = todo_items
        context['completed_items'] = completed_items
        context['category_list'] = category_list
        context['form'] = self.form
        return context


class CompletedTodoListView(ListView):
    model = Todo
    template_name = 'main/completed_todos.html'
    context_object_name = 'completed_todos'


    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = Todo.objects.filter(
            status=True,
            user_id=self.request.user.id
        ).order_by("-added_date")
        return queryset


    # def get_context_data(self, **kwargs):
    #     completed_todos = Todo.objects.filter(status=True, user_id=self.request.user.id).order_by("-added_date")
    #     context = super().get_context_data(**kwargs)
    #     context['completed_todos'] = completed_todos
    #     return context
    

#There are some views for ajax_requests


def add_new_ajax(request):
    current_date = timezone.now()
    content = request.POST["text"]
    category = Category.objects.get(id=request.POST["categ"])
    date = request.POST['date']
    if date == '':
        date = str(current_date)[:10] + ' 23:59'
    if content != "":
        complete = False
        created_obj = Todo.objects.create(
            added_date=current_date,
            text=content,
            status=complete,
            user_id=request.user.id,
            category=category,
            deadline=date
        )
        created_obj.save()
    else:
        messages.warning(request, 'Fill up task field!')
    return JsonResponse({})


def complete_todo_ajax(request, todo_id):

    completed = Todo.objects.get(id=todo_id)
    completed.status = True
    completed.save()

    user_id = request.user.id
    active_profile = Profile.objects.get(user=user_id)
    active_profile.number_of_todos += 1
    active_profile.save()

    return JsonResponse({})


def delete_todo_ajax(request, todo_id):
    Todo.objects.get(id=todo_id).delete()
    return JsonResponse({})


#There are some func-based views

def category_template(request, category_id):

    selected_category = Category.objects.get(id=category_id)
    todos_in_category = Todo.objects.filter(status=False, user_id=request.user.id, category=category_id).order_by("deadline")
    category_list = Category.objects.all()

    context = {
        'selected_category': selected_category,
        'todos_in_category': todos_in_category,
        'category_list': category_list
    }

    return render(request, 'main/category_template.html', context)


def timer(request):
    category_list = Category.objects.all()
    context = {

        'category_list': category_list
    }

    return render(request, 'main/timer.html', context)

main/templates/main/category_template.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <div class="row mt-4">
        <div class="col">
            <ul class="list-group">
                {% if todos_in_category %}
                <h2>{{ selected_category }}</h2>
                {% for todo_in_category in todos_in_category %}
                    <li class="list-group-item mb-2 mt-2">{{ todo_in_category.text }}

                            <button type="button" 
                            {% if todo_in_category.category.title == "General" %}
                                class="ml-2 btn btn-primary"
                            {% elif todo_in_category.category.title == "Work" %}
                                class="ml-2 btn btn-success"
                            {% elif todo_in_category.category.title == "Health/Body" %}
                                class="ml-2 btn btn-warning"
                            {% elif todo_in_category.category.title == "Study" %}
                                class="ml-2 btn btn-danger"
                            {% elif todo_in_category.category.title == "Body" %}
                                class="ml-2 btn btn-info"
                            {% elif todo_in_category.category.title == "Other" %}
                                class="ml-2 btn btn-secondary"
                            {% endif %}
                            >{{ todo_in_category.category}}</button>

                        <div class="float-right">   
                            <form class="my_class_complete" id="todo_{{ todo_in_category.pk }}" data-href="{% url 'complete_todo_ajax' todo_in_category.pk %}" method="post"> {% csrf_token %}
                                <button type="submit" class="btn btn-success">l have already did this</button>
                            </form>
                        </div>
                    </li>
                {% endfor %}

                {% else %}

                <h2 class="mt-5 text-center">Oops... Seems, like you haven't got tasks in this category</h2>

                <form action="{% url 'home' %}"> {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-lg btn-block mt-2">Add new ToDo</button>
                </form>   

                {% endif %}

                {% if completed_items %}
                <h2>Last completed tasks:</h2>
                {% for completed_item in completed_items %}
                    <li class="list-group-item text-muted mt-2">{{ completed_item.text }}
                        <div class="float-right">   
                            <form class="my_class_delete" id="todo_{{ completed_item.pk }}" data-href="{% url 'delete_todo_ajax' completed_item.pk %}" method="post"> {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </li>
                {% endfor %}
                {% endif %}

                
            </ul>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'main/js/scripts.js' %}"></script>
{% endblock %}

main/templates/main/completed_todos.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <h2>Last completed tasks:</h2>

    <div class="row mt-4">
        <div class="col">
            <div id="completed_table">
            <ul class="list-group" id="completed">
                {% for completed_todo in completed_todos %}
                    <li class="list-group-item text-muted mt-2">{{ completed_todo.text }} 
                        <div class="float-right">   
                            <form class="my_class_delete_list" id="todo_{{ completed_todo.pk }}" data-href="{% url 'delete_todo_ajax' completed_todo.pk %}" method="post"> {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </li>
                {% endfor %}               
            </ul>
        </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'main/js/scripts.js' %}"></script>
{% endblock %}

main/templates/main/todo_list.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}


{% block head %}
{% endblock head %}

{% block content %}

  <div id='add_new_div' class="row mt-4">
        <div class="col-12">
            <h2>What have you to do?</h2>
            <form id="add_new" method="post"> {% csrf_token %}

                {{ form.text| as_crispy_field }}

                <label for="category_select" class="requiredField">
                    Category<span class="asteriskField">*</span>
                </label>
                <select id="category_select" class="font-italic custom-select mb-2">
                  {% for category in category_list %}
                    <option id="{{category.id}}">{{ category.title }}</option>
                  {% endfor %}
                </select>
                
                <label for="id_deadline" class="requiredField">
                    Deadline
                </label>
                {{ form.deadline  }}

                <button type="submit" id="add_button" class="btn btn-primary btn-lg btn-block mt-4">Add</button>

            </form>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-12">
            <ul class="list-group" id="ul_coming">
                <div id="coming_tasks">
                {% if todo_items %}
                <h3 id="coming_tasks_h2">Coming tasks:</h3>
                  {% for todo_item in todo_items %}
                
                    <li class="list-group-item mb-2">
                        <span id="todo_item_text">{{ todo_item.text }}</span>
                        <button type="submit" 
                            {% if todo_item.category.title == "General" %}
                                class="ml-2 btn btn-primary"
                            {% elif todo_item.category.title == "Work" %}
                                class="ml-2 btn btn-success"
                            {% elif todo_item.category.title == "Health/Body" %}
                                class="ml-2 btn btn-warning"
                            {% elif todo_item.category.title == "Study" %}
                                class="ml-2 btn btn-danger"
                            {% elif todo_item.category.title == "Body" %}
                                class="ml-2 btn btn-info"
                            {% elif todo_item.category.title == "Other" %}
                                class="ml-2 btn btn-secondary"
                            {% endif %}
                            ><a id="category_button" href="{% url 'category_template' todo_item.category.id %}">{{ todo_item.category}}</a></button>

                        <div class="float-right">   
                            <form class="my_class_complete" data-href="{% url 'complete_todo_ajax' todo_item.pk %}" method="post"> {% csrf_token %}
                                <button type="submit" class="btn btn-success" id="complete_button_{{ todo_item.pk }}">l have already did this</button>
                            </form>
                        </div>
                    </li>
                {% endfor %}
                </div>
                {% endif %}
             </ul>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'main/js/gijgo.min.js' %}"></script>
    <script>
        $('#id_deadline').datetimepicker({ 
            footer: true, 
            modal: true,
            format: 'yyyy-mm-dd HH:MM',
            uiLibrary: 'bootstrap4' 
            });
    </script>
    <script src="{% static 'main/js/scripts.js' %}"></script>
{% endblock %}